config/routes.rb
Rails.application.routes.draw do

  get 'competing_users/edit' => 'competing_users#edit', as: :edit_competing_user
  post 'competing_users/select_favorite_competing_team' => 'competing_users#select_favorite_competing_team', as: :select_favorite_competing_team
  get 'static_pages/rules' => 'static_pages#rules', as: :rules
  get "/rules", :to => "static_pages#rules", :as => :ruly_rules

  get 'matches/:user_id/:is_finished/:limit/:round_id' => 'matches#index', as: :matches

  resources :competitions
  resources :departments
  devise_for :users
  get 'dashboard/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/award.rb
class Award < ApplicationRecord
end

app/models/competing_team.rb
class CompetingTeam < ApplicationRecord
  belongs_to :group
  belongs_to :team
  has_many :home_matches, class_name: "Match", foreign_key: "competing_team_home"
  has_many :away_matches, class_name: "Match", foreign_key: "competing_team_away"

  # Get all matches
  def matches
    self.home_matches + self.away_matches
  end
end

app/models/competing_user.rb
class CompetingUser < ApplicationRecord
  belongs_to :user
  belongs_to :competition
  belongs_to :competing_team, optional: true
  has_many :round_rankings

  def success_perc
    return 0 if predictions.zero?
    (success * 100) / predictions
  end

end

app/models/competition.rb
class Competition < ApplicationRecord
  belongs_to :competition_structure
  has_many :groups
  has_many :competing_users
  has_many :competing_departments
  has_one :ranking

  def competing_user_favorite_team_deadline
    self.begin + 1.week.to_i
  end

end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/day_stadistic.rb
class DayStadistic < ApplicationRecord
  belongs_to :department, optional: true
  belongs_to :competing_user, optional: true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :competing_departments
  has_many :users
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :competition
  has_many :competing_teams
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :country
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :competing_team_home, class_name: "CompetingTeam"
  belongs_to :competing_team_away, class_name: "CompetingTeam"
  belongs_to :stadium
  belongs_to :round
  has_many :predictions
  has_many :match_stadistics

  def prediction_by_competing_user(competing_user)
    # TODO: Select with caching
    predictions.find { |p| p.competing_user_id == competing_user.id }
  end

  def global_stadistics
    # TODO: Select with caching
    match_stadistics.find { |ms| ms.department_id.nil? }
  end

  def match_stadistics_by_department(department)
    # TODO: Select with caching
    match_stadistics.find { |ms| ms.department_id == department.id }
  end

end

app/models/match_stadistic.rb
class MatchStadistic < ApplicationRecord
  belongs_to :match
  belongs_to :department, optional: true
end

app/models/prediction.rb
class Prediction < ApplicationRecord
  belongs_to :competing_user
  belongs_to :match
  belongs_to :prediction_result
  has_many :competing_user_awards

  validates_uniqueness_of :competing_user_id, :scope => :match_id
end

app/models/prediction_result.rb
class PredictionResult < ApplicationRecord
end

app/models/round.rb
class Round < ApplicationRecord
  belongs_to :competition
  has_many :round_rankings
end

app/models/round_ranking.rb
class RoundRanking < ApplicationRecord
  belongs_to :competing_user
  belongs_to :round

  validates_uniqueness_of :competing_user_id, scope: :round_id
end

app/models/stadium.rb
class Stadium < ApplicationRecord
  belongs_to :location
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :competing_teams
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable, :trackable

  enum role: [:user, :admin]
  belongs_to :department
  has_many :competing_users

  validates :name, presence: true, length: {maximum:50}
  validates :first_name,  presence: true, length: {maximum:50}
  validates :last_name, presence: true, length: {maximum:50}
  validates :department_id, presence: true
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :set_competition, only: %i[ show edit update destroy ]

  # GET /competitions or /competitions.json
  def index
    @competitions = Competition.all
  end

  # GET /competitions/1 or /competitions/1.json
  def show
  end

  # GET /competitions/new
  def new
    @competition = Competition.new
  end

  # GET /competitions/1/edit
  def edit
  end

  # POST /competitions or /competitions.json
  def create
    @competition = Competition.new(competition_params)

    respond_to do |format|
      if @competition.save
        format.html { redirect_to competition_url(@competition), notice: "Competition was successfully created." }
        format.json { render :show, status: :created, location: @competition }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /competitions/1 or /competitions/1.json
  def update
    respond_to do |format|
      if @competition.update(competition_params)
        format.html { redirect_to competition_url(@competition), notice: "Competition was successfully updated." }
        format.json { render :show, status: :ok, location: @competition }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1 or /competitions/1.json
  def destroy
    @competition.destroy

    respond_to do |format|
      format.html { redirect_to competitions_url, notice: "Competition was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_competition
      @competition = Competition.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def competition_params
      params.require(:competition).permit(:name, :competition_structure_id, :national_teams, :groups, :teams_group, :rounds, :begin, :active, :loops)
    end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/flag_src_helper.rb
module FlagSrcHelper
  def flag_src(iso_alpha2)
    src = iso_alpha2.nil? ? "xx" : iso_alpha2.downcase
    "/assets/flags/4x3/" + src + ".svg"
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/competitions/_competition.html.erb
<div id="<%= dom_id competition %>">
  <p>
    <strong>Name:</strong>
    <%= competition.name %>
  </p>

  <p>
    <strong>Competition structure:</strong>
    <%= competition.competition_structure_id %>
  </p>

  <p>
    <strong>National teams:</strong>
    <%= competition.national_teams %>
  </p>

  <p>
    <strong>Groups:</strong>
    <%= competition.groups %>
  </p>

  <p>
    <strong>Teams group:</strong>
    <%= competition.teams_group %>
  </p>

  <p>
    <strong>Rounds:</strong>
    <%= competition.rounds %>
  </p>

  <p>
    <strong>Begin:</strong>
    <%= competition.begin %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= competition.active %>
  </p>

  <p>
    <strong>Loops:</strong>
    <%= competition.loops %>
  </p>

</div>

app/views/competitions/_form.html.erb
<%= form_with(model: competition) do |form| %>
  <% if competition.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

      <ul>
        <% competition.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :competition_structure_id, style: "display: block" %>
    <%= form.text_field :competition_structure_id %>
  </div>

  <div>
    <%= form.label :national_teams, style: "display: block" %>
    <%= form.check_box :national_teams %>
  </div>

  <div>
    <%= form.label :groups, style: "display: block" %>
    <%= form.number_field :groups %>
  </div>

  <div>
    <%= form.label :teams_group, style: "display: block" %>
    <%= form.number_field :teams_group %>
  </div>

  <div>
    <%= form.label :rounds, style: "display: block" %>
    <%= form.number_field :rounds %>
  </div>

  <div>
    <%= form.label :begin, style: "display: block" %>
    <%= form.datetime_field :begin %>
  </div>

  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.check_box :active %>
  </div>

  <div>
    <%= form.label :loops, style: "display: block" %>
    <%= form.number_field :loops %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/competitions/edit.html.erb
<h1>Editing competition</h1>

<%= render "form", competition: @competition %>

<br>

<div>
  <%= link_to "Show this competition", @competition %> |
  <%= link_to "Back to competitions", competitions_path %>
</div>

app/views/competitions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Competitions</h1>

<div id="competitions">
  <% @competitions.each do |competition| %>
    <%= render competition %>
    <p>
      <%= link_to "Show this competition", competition %>
    </p>
  <% end %>
</div>

<%= link_to "New competition", new_competition_path %>

app/views/competitions/new.html.erb
<h1>New competition</h1>

<%= render "form", competition: @competition %>

<br>

<div>
  <%= link_to "Back to competitions", competitions_path %>
</div>

app/views/competitions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @competition %>

<div>
  <%= link_to "Edit this competition", edit_competition_path(@competition) %> |
  <%= link_to "Back to competitions", competitions_path %>

  <%= button_to "Destroy this competition", @competition, method: :delete %>
</div>