config/routes.rb
Rails.application.routes.draw do

  get 'competing_users/edit' => 'competing_users#edit', as: :edit_competing_user
  post 'competing_users/select_favorite_competing_team' => 'competing_users#select_favorite_competing_team', as: :select_favorite_competing_team
  get 'static_pages/rules' => 'static_pages#rules', as: :rules
  get "/rules", :to => "static_pages#rules", :as => :ruly_rules

  get 'matches/:user_id/:is_finished/:limit/:round_id' => 'matches#index', as: :matches

  resources :competitions
  resources :departments
  devise_for :users
  get 'dashboard/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/award.rb
class Award < ApplicationRecord
end

app/models/competing_team.rb
class CompetingTeam < ApplicationRecord
  belongs_to :group
  belongs_to :team
  has_many :home_matches, class_name: "Match", foreign_key: "competing_team_home"
  has_many :away_matches, class_name: "Match", foreign_key: "competing_team_away"

  # Get all matches
  def matches
    self.home_matches + self.away_matches
  end
end

app/models/competing_user.rb
class CompetingUser < ApplicationRecord
  belongs_to :user
  belongs_to :competition
  belongs_to :competing_team, optional: true
  has_many :round_rankings

  def success_perc
    return 0 if predictions.zero?
    (success * 100) / predictions
  end

end

app/models/competition.rb
class Competition < ApplicationRecord
  belongs_to :competition_structure
  has_many :groups
  has_many :competing_users
  has_many :competing_departments
  has_one :ranking

  def competing_user_favorite_team_deadline
    self.begin + 1.week.to_i
  end

end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/day_stadistic.rb
class DayStadistic < ApplicationRecord
  belongs_to :department, optional: true
  belongs_to :competing_user, optional: true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :competing_departments
  has_many :users
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :competition
  has_many :competing_teams
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :country
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :competing_team_home, class_name: "CompetingTeam"
  belongs_to :competing_team_away, class_name: "CompetingTeam"
  belongs_to :stadium
  belongs_to :round
  has_many :predictions
  has_many :match_stadistics

  def prediction_by_competing_user(competing_user)
    # TODO: Select with caching
    predictions.find { |p| p.competing_user_id == competing_user.id }
  end

  def global_stadistics
    # TODO: Select with caching
    match_stadistics.find { |ms| ms.department_id.nil? }
  end

  def match_stadistics_by_department(department)
    # TODO: Select with caching
    match_stadistics.find { |ms| ms.department_id == department.id }
  end

end

app/models/match_stadistic.rb
class MatchStadistic < ApplicationRecord
  belongs_to :match
  belongs_to :department, optional: true
end

app/models/prediction.rb
class Prediction < ApplicationRecord
  belongs_to :competing_user
  belongs_to :match
  belongs_to :prediction_result
  has_many :competing_user_awards

  validates_uniqueness_of :competing_user_id, :scope => :match_id
end

app/models/prediction_result.rb
class PredictionResult < ApplicationRecord
end

app/models/round.rb
class Round < ApplicationRecord
  belongs_to :competition
  has_many :round_rankings
end

app/models/round_ranking.rb
class RoundRanking < ApplicationRecord
  belongs_to :competing_user
  belongs_to :round

  validates_uniqueness_of :competing_user_id, scope: :round_id
end

app/models/stadium.rb
class Stadium < ApplicationRecord
  belongs_to :location
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :competing_teams
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable, :trackable

  enum role: [:user, :admin]
  belongs_to :department
  has_many :competing_users

  validates :name, presence: true, length: {maximum:50}
  validates :first_name,  presence: true, length: {maximum:50}
  validates :last_name, presence: true, length: {maximum:50}
  validates :department_id, presence: true
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: %i[ show edit update destroy ]

  # GET /departments or /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1 or /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments or /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to department_url(@department), notice: "Department was successfully created." }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1 or /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to department_url(@department), notice: "Department was successfully updated." }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1 or /departments/1.json
  def destroy
    @department.destroy

    respond_to do |format|
      format.html { redirect_to departments_url, notice: "Department was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def department_params
      params.require(:department).permit(:name)
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/flag_src_helper.rb
module FlagSrcHelper
  def flag_src(iso_alpha2)
    src = iso_alpha2.nil? ? "xx" : iso_alpha2.downcase
    "/assets/flags/4x3/" + src + ".svg"
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/departments/_department.html.erb
<div id="<%= dom_id department %>">
  <p>
    <strong>Name:</strong>
    <%= department.name %>
  </p>

</div>

app/views/departments/_form.html.erb
<%= form_with(model: department) do |form| %>
  <% if department.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
        <% department.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing department</h1>

<%= render "form", department: @department %>

<br>

<div>
  <%= link_to "Show this department", @department %> |
  <%= link_to "Back to departments", departments_path %>
</div>

app/views/departments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Departments</h1>

<div id="departments">
  <% @departments.each do |department| %>
    <%= render department %>
    <p>
      <%= link_to "Show this department", department %>
    </p>
  <% end %>
</div>

<%= link_to "New department", new_department_path %>

app/views/departments/new.html.erb
<h1>New department</h1>

<%= render "form", department: @department %>

<br>

<div>
  <%= link_to "Back to departments", departments_path %>
</div>

app/views/departments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @department %>

<div>
  <%= link_to "Edit this department", edit_department_path(@department) %> |
  <%= link_to "Back to departments", departments_path %>

  <%= button_to "Destroy this department", @department, method: :delete %>
</div>